name: Oxygen XML/JSON - Validate Files
description: Validation for XML, XSL, XQuery, XSD, JSON, YAML, HTML, CSS, WSDL, DITA, RNG, DTD and other schemas using Oxygen Scripting
branding:
  icon: 'check-square'
  color: 'blue'
inputs:
  validationDir:
    description: The name of directory containing the files to be validated.
    required: true
    default: validation
runs:
  using: "composite"
  steps:
    - name: Checkout current repo.
      uses: actions/checkout@v3.3.0
      
    - name: Checkout Oxygen Scripting Template repo.
      uses: actions/checkout@v3.3.0
      with:
        repository: oxygenxml/oxygen-script-validation-template
        path: scripting
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Make gradlew executable
      run: chmod +x ./scripting/build/gradlew
      shell: bash

    - name: Build with Gradle
      run: cd scripting/build; ./gradlew runValidation -PvalidationDir=${{ inputs.validationDir }} -PlocalBuild=false --info --stacktrace --build-cache
      shell: bash

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        folder: scripting/report # The folder the action should deploy.
